CREATE TABLE CUSTOMER (
  ID INTEGER NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CUSTOMER_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE TABLE AUTHORITIES(
	ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	NAME varchar(50),
	PRIMARY KEY (ID),
	FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE SEQUENCE AUTHORITIES_SEQ
	AS INTEGER
	START WITH 1
	INCREMENT BY 1
	CACHE 10;


<<<<<<< HEAD
--Test data
INSERT INTO DB2INST1.AUTHORITIES (ID,CUSTOMER_ID,NAME) VALUES
	 (1,1,'VIEW_SITE_ONE'),
	 (2,1,'VIEW_SITE_TWO'),
	 (3,1,'VIEW_SITE_THREE'),
	 (4,2,'VIEW_SITE_ONE'),
	 (5,2,'VIEW_SITE_TWO');

INSERT INTO DB2INST1.CUSTOMER (ID,EMAIL,PASSWORD,"ROLE") VALUES
	 (1,'admin@example.com','{bcrypt}$2a$12$ONwecI4uUr37Ue7FPsDSdeDQUs6RwkUppzwjAgikZMPicmu9K690.','admin'),
	 (2,'user@example.com','{bcrypt}$2a$12$ONwecI4uUr37Ue7FPsDSdeDQUs6RwkUppzwjAgikZMPicmu9K690.','user');
=======


--Test data
INSERT INTO CUSTOMER (ID, EMAIL, PASSWORD, ROLE)
VALUES 
('1', 'admin@example.com', '{bcrypt}$2a$12$/fOPV31EH3jAjkwhRyCJAe8kZZr5NusLwq.c3.eiviTy5I9oyJcD.', 'admin');


INSERT INTO AUTHORITIES 
(ID, CUSTOMER_ID, NAME)
VALUES
('1','1','VIEW_SITE_ONE'),
('2','1','VIEW_SITE_TWO'),
('3','1','VIEW_SITE_THREE');


>>>>>>> 983c584 (added authorities)
