CREATE TABLE CUSTOMER (
  ID INTEGER NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CUSTOMER_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

--Test data
INSERT INTO CUSTOMER (ID, EMAIL, PASSWORD, ROLE)
VALUES ('1', 'admin@example.com', '{bcrypt}$2a$12$/fOPV31EH3jAjkwhRyCJAe8kZZr5NusLwq.c3.eiviTy5I9oyJcD.', 'admin');
