CREATE TABLE CUSTOMER (
  ID INTEGER NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CUSTOMER_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
